"""Add firstname lastname to user

Revision ID: c4f6d1767778
Revises: cecd2e46742d
Create Date: 2024-11-08 20:34:43.326381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f6d1767778'
down_revision: Union[str, None] = 'cecd2e46742d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=36), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
